import Rutas from '../../components/Rutas'
import './globals.css'
import { TasksProvider } from '@/context/TasksContext'
import Home from './page'



export const metadata = {
  title: 'Proyecto',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-100'>
        <Rutas>
          <TasksProvider>{children}</TasksProvider>
        </Rutas>       
      </body>
    </html>
  )
}
